### ISSUE TITLE
Move Tessel Shop Links to Seeed's Store

### ISSUE THREAD

**Issue by johnnyman727** [tessel/project#119] opened 2015-12-08 20:56 UTC
Celery (the storefront provider) is changing their API on January 1st which will more than likely throw off our integration with Whiplash (for fulfillment).

We should plan to change all store links to point to the corresponding item in Seeed Studio store before then.

This requires:
- [ ] Have Seeed add a T2 pre-order page (@johnnymany727)
- [x] Modify all existing module links to point to the existing module links within Seeed's store. (@tcr)

**Comment by Frijol** [comment] 2016-01-25 20:54
Duplicate of https://github.com/tessel/tessel.io/issues/33

**Closed by Frijol** 2016-01-25 20:54 UTC
